extends: ['airbnb-typescript']

parserOptions:
  project: './tsconfig.json'

rules: {
    # arrow-body-style: ["error", "always"],
    no-param-reassign: ["error", { "props": false }],
    react/prop-types: 0,
    # max-len: "off",
    jsx-a11y/click-events-have-key-events: "off",
    jsx-a11y/no-static-element-interactions: "off",
    jsx-a11y/no-noninteractive-tabindex: "off",
    jsx-a11y/no-noninteractive-element-interactions: "off",
    jsx-a11y/label-has-associated-control: "off",
    arrow-body-style: "off",
}
